export default {
  GET_CAMPUS: 'GET_CAMPUS',
  GET_CAMPUSES: 'GET_CAMPUSES',
  GET_STUDENT: 'GET_STUDENT',
  GET_STUDENTS: 'GET_STUDENTS',
  ADD_CAMPUS: 'ADD_CAMPUS',
  ADD_STUDENT: 'ADD_STUDENT',
  DELETE_CAMPUS: 'DELETE_CAMPUS',
  DELETE_STUDENT: 'DELETE_STUDENT',
  UPDATE_CAMPUS: 'UPDATE_CAMPUS',
  UPDATE_STUDENT: 'UPDATE_STUDENT',
};
